pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        },
        stage('Result'){
            steps{
                echo "Result collected"
            }
        }

        stage('Deliver') {
            steps {
                echo "Deliver complete"
            }
        }
    }
}
